sugar:
  id: 1
  server: LarsSugar
  url: http://rhomobile.com/sugar/soap.php?wsdl
  login: admin
  password: acc3ss$ugar
  prolog: |
    u = @source.login
    p = Digest::MD5.hexdigest(@source.password)
    ua = {"user_name" => u,"password" => p}
    ss = client.login(ua,nil)
    if ss.error.number.to_i != 0
      p "failed to login - #{ss.error.description}"
      return
    else
      session_id = ss['id']
      uid = client.get_user_id(session_id)
      p "logged in to session #{session_id} as #{u} (#{uid}) "
    end

  call: |
    module_name = "Accounts"
    query = "" # gets all the acounts, you can also use SQL like "accounts.name like '%company%'"
    order_by = "" # in default order. you can also use SQL like "accounts.name"
    offset = 0 # I guess this is like the SQL offset
    select_fields = ['name','industry'] # this can't be an empty array, my testing showed
    max_results = "1000000" # if set to 0 or "", this doesn't return all the results, like you'd expect
    deleted = 0 # whether you want to retrieve deleted records, too
    result = client.get_entry_list(session_id,module_name,query,order_by,offset,select_fields,max_results,deleted);

  sync: |
    result.entry_list.each do |x|
      x.name_value_list.each do |y|
        o=ObjectValue.new
        o.source_id=@source.id
        o.object=x.id
        o.attribute=y.name
        o.value=y.value
        o.updatetype="update"
        o.save
      end
    end

  create:
    # name_value_list is passed in and can be used in the code below
    # for creates we just assume that the primary keys (if fields) are left out
    result=client.set_entry(session_id,'Accounts',name_value_list)

  update:
    # name_value_list is passed in and can be used in the code below
    result=client.set_entry(session_id,'Accounts',name_value_list)

  delete:
    result=client.set_entry(session_id,'Accounts',name_value_list)







